In [1]:
import numpy as np

In [5]:
arr0 = np.array(3)
print(arr0)
print(arr0.shape)

3
()


In [6]:
arr1 = np.array([4, 5, 6])
print(arr1)
print(arr1.shape)

[4 5 6]
(3,)


In [7]:
arr2 = np.array([[7, 8, 9], [1, 2, 3]])
print(arr2)
print(arr2.shape)


[[7 8 9]
 [1 2 3]]
(2, 3)


In [8]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 7, 8, 9], [10, 11, 12, 14, 15]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  7  8  9]
 [10 11 12 14 15]]
(3, 5)


In [9]:
arr4 = np.array([
    [[1, 2, 3, 4, 5]], [[6, 7, 7, 8, 9]],
    [[10, 11, 12, 14, 15]], [[5, 10, 15, 20, 25]]
    ])
print(arr4)
print(arr4.shape)

[[[ 1  2  3  4  5]]

 [[ 6  7  7  8  9]]

 [[10 11 12 14 15]]

 [[ 5 10 15 20 25]]]
(4, 1, 5)


In [10]:
zeros_arr = np.zeros((4, 3))
print(zeros_arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
ones_arr = np.ones((4, 3))
print(ones_arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
fill_arr = np.full((2, 3), 7)
print(fill_arr)

[[7 7 7]
 [7 7 7]]


In [13]:
id_matrix1 = np.eye(5, 5)
print(id_matrix1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
array_range = np.arange(1, 9, 3)
print(array_range)

[1 4 7]


In [15]:
arr_float = np.random.rand(12, 6)
print(arr_float)

[[0.01548584 0.45614784 0.77104808 0.42590909 0.34415495 0.48410312]
 [0.76309671 0.1309016  0.64118114 0.57231635 0.6989085  0.96017571]
 [0.59566094 0.71434058 0.81605205 0.39377448 0.2350912  0.60999657]
 [0.97542907 0.25770397 0.44156288 0.13719034 0.95031321 0.99706848]
 [0.13117733 0.14623909 0.75970507 0.53117369 0.11384236 0.70604602]
 [0.99397101 0.39847152 0.59017636 0.43240076 0.72168616 0.30969666]
 [0.95042526 0.78174075 0.67009587 0.69332221 0.61877829 0.00945662]
 [0.25056624 0.17916263 0.00153854 0.20201113 0.3461222  0.01484637]
 [0.66018284 0.39554095 0.25414818 0.74810609 0.57129505 0.35618709]
 [0.4622276  0.68460697 0.93860998 0.92419678 0.15091004 0.01992541]
 [0.76158475 0.84100639 0.26945162 0.66098513 0.59746394 0.95873479]
 [0.4020147  0.71363804 0.64625598 0.78767475 0.68850193 0.19535122]]


In [16]:
arr_int = np.random.randint(2, 8, (2, 4))
print(arr_int)

[[6 4 7 5]
 [4 4 7 6]]


In [17]:
print(arr2)

[[7 8 9]
 [1 2 3]]


In [18]:
print(arr2.shape)

(2, 3)


In [19]:
print(arr2.ndim)

2


In [20]:
print(arr2.size)

6


In [21]:
print(arr2.dtype)

int64


In [24]:
arr_access = np.array([3, 7, 9, 7, 9, 6])
print(f"Array:{arr_access}")

Array:[3 7 9 7 9 6]


In [25]:
first_elem = arr_access[0]
print(f"First element:{first_elem}")


First element:3


In [27]:
last_elem = arr_access[-2]
print(f"Last element:{last_elem}")


Last element:9


In [28]:
slice_array = np.array([1, 2, 3, 4, 5, 6, 7])
print(slice_array[:2])

[1 2]


In [29]:
slice_array = np.array([1, 2, 3, 4, 5, 6, 7])
print(slice_array[2:])

[3 4 5 6 7]


In [31]:
vectorized_array = np.array([20, 30, 40, 50, 60])
print(vectorized_array + 30)

[50 60 70 80 90]


In [33]:
arr_mod1 = np.array([1, 2, 3, 4])
arr_mod2 = np.array([5, 6, 7, 8])
print(f"divide_result: ({arr_mod1 / arr_mod2}")
print()
print(f"add_result: ({arr_mod1 + arr_mod2}")
print()
print(f"subtract_result: ({arr_mod1 - arr_mod2}")

divide_result: ([0.2        0.33333333 0.42857143 0.5       ]

add_result: ([ 6  8 10 12]

subtract_result: ([-4 -4 -4 -4]


In [35]:
arr_mod1[1] = 6
print(f"modified_arr: {arr_mod1}")

modified_arr: [1 6 3 4]


In [40]:
arr_def = np.array([2, 4, 6, 8, 10, 12, 14, 16])
reshaped_arr = arr_def.reshape(2,4)
print(reshaped_arr)

[[ 2  4  6  8]
 [10 12 14 16]]


In [41]:
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)
print(flattened_arr.shape)

[ 2  4  6  8 10 12 14 16]
(8,)


In [42]:
random_num = np.random.rand()
print(random_num)

0.39903484010746204


In [43]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.32150079 0.44832252 0.49022512]
 [0.50944624 0.51779198 0.04138338]
 [0.72916445 0.82883436 0.27476172]]


In [49]:
random_int1 = np.random.randint(1, 5)
print(f"single: {random_int1}")
print()

single: 1



In [52]:
random_int2 = np.random.randint(1, 10, size=3)
print(f"multiple: {random_int2}")
print()

multiple: [7 3 2]



In [53]:
random_int3 = np.random.randint(1, 1000, (5, 10))
print(f"2_dimension:\n {random_int3}")
print()

2_dimension:
 [[726  98  39  74 246 178 436 887  94 493]
 [517 188 163 974 620 444 783 740 331 738]
 [ 46 556 233 958 735 691 208 702 298 119]
 [511 402 211 190 752 515 507 246 153 633]
 [743 863 326 447 731 661 749 759 419 514]]



In [55]:
arr_new = np.array ([6, 4, 2, 1])
print(np.sum(arr_new))

13


In [56]:
arr_new = np.array ([6, 4, 2, 1])
print(np.mean(arr_new))

3.25


In [57]:
arr_new = np.array ([6, 4, 2, 1])
print(np.median(arr_new))

3.0


In [58]:
arr_new = np.array ([6, 4, 2, 1])
print(np.std(arr_new))

1.920286436967152


In [59]:
random_int = np.random.randint(1, 100, (3, 4))
print(f"2_dimension:\n {random_int}")
print()

2_dimension:
 [[92 29 40  3]
 [97 21  5 83]
 [32 55 18 54]]



In [76]:
slice_array = random_int
print(slice_array[:2, -3:][slice_array[:2, -3:] % 2 == 0])



[40]


In [78]:
reshaped_arr = random_int.reshape(2, 2, 3)
print(reshaped_arr)
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)
print(flattened_arr.shape)


[[[92 29 40]
  [ 3 97 21]]

 [[ 5 83 32]
  [55 18 54]]]
[92 29 40  3 97 21  5 83 32 55 18 54]
(12,)


In [83]:
id_matrix1 = np.eye(4, 4)
np.fill_diagonal(id_matrix1, np.arange(10, 50, 10))
print(id_matrix1)

[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [91]:
rand_matrix1 = np.random.randint(1, 11, size =(3, 4))
print(rand_matrix1)
rand_matrix2 = np.random.randint(1, 11, size=(4, 3))
print(rand_matrix2)
result = rand_matrix1 @ rand_matrix2
print(result)

[[ 2  4  2 10]
 [ 1  1  3  9]
 [ 8  1  7  9]]
[[ 1  5  5]
 [ 7  3  9]
 [ 8  3  2]
 [10  8  2]]
[[146 108  70]
 [122  89  38]
 [161 136  81]]


In [6]:
def new_arr(arr):
    result = arr.copy()
    result[arr % 2 ==0] = result[arr % 2 == 0] **2
    result[arr % 2 !=0] = -1
    return result

In [8]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(arr)
print(new_arr(arr))

[[1 2 3 4]
 [5 6 7 8]]
[[-1  4 -1 16]
 [-1 36 -1 64]]
